openapi: 3.0.0
info:
  title: Sample API
  description: API for creating and fetching post and user activities log.
  version: 1.0.0


paths:
  /api/v1/posts:
     post:
      summary: Create a new post
      description: Endpoint to create a new post.
      requestBody:
        description: post details and object that needs to be created
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  type: string
                  example: information of context
                title:
                  type: string
                  example: Title of the context
                image:
                  type: string
                  format: uri
                  example: https://image.png
                userId:
                  type: string
                  format: uuid
                  example: 123e4567-e89b-12d3-a456-426614174000
                createdAt:
                  type: string
                  format: date-time
                  example: 2023-01-19:12:00
                updatedAt:
                  type: string
                  format: date-time
                  example: 2023-01-19:12:00
              required:
                - context
                - title
                - userId
                - createdAt
                - updatedAt
      responses:
        '201':
          description: post created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  context:
                    type: string
                    example: information of context
                  title:
                    type: string
                    example: Title of the context
                  image:
                    type: string
                    format: uri
                    example: https://example.com/image.png
                  userId:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  createdAt:
                    type: string
                    format: date-time
                    example: 2023-01-19:12:00
                  updatedAt:
                    type: string
                    format: date-time
                    example: 2023-01-19:12:00
      
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid input provided 
     get:
      summary: Get all post
      description: Endpoint to get all post.
      responses:
        '200':
          description: post retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                      example: 123e4567-e89b-12d3-a456-426614174000
                    context:
                      type: string
                      example: information of context
                    title:
                      type: string
                      example: Title of the context
                    image:
                      type: string
                      format: uri
                      example: https://example.com/image.png
                    userId:
                      type: string
                      format: uuid
                      example: 123e4567-e89b-12d3-a456-426614174000
                    createdAt:
                      type: string
                      format: date-time
                      example: 2023-01-19:12:00
                    updatedAt:
                      type: string
                      format: date-time
                      example: 2023-01-19:12:00
        '404':
          description: No resources found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No resources found
  /api/v1/posts/{postId}:
     get:
      summary: Get a post by postId
      description: Endpoint to get a post by its postId.
      
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the post to retrieve
      responses:
        '200':
          description: post retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  context:
                    type: string
                    example: information of context
                  title:
                    type: string
                    example: Title of the context
                  image:
                    type: string
                    format: uri
                    example: https://example.com/image.png
                  userId:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  createdAt:
                    type: string
                    format: date-time
                    example: 2023-01-19:12:00
                  updatedAt:
                    type: string
                    format: date-time
                    example: 2023-01-19:12:00
        '404':
          description: post not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: post not found
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid ID supplied
     delete:
       summary: Delete a post by postId
       description: Endpoint to delete a post by its postId.
       parameters:
         - name: postId
           in: path
           required: true
           schema:
            type: string
            format: uuid
            description: The UUID of the resource to delete
       responses:
        '204':
          description: post deleted successfully
        '404':
          description: post not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: post not found
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid ID supplied 
     patch:
       summary: Update a post by postId
       requestBody:
        description: post details and object that needs to be created
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  type: string
                  example: information of context
                title:
                  type: string
                  example: Title of the context
                image:
                  type: string
                  format: uri
                  example: https://image.png
                userId:
                  type: string
                  format: uuid
                  example: 123e4567-e89b-12d3-a456-426614174000
                createdAt:
                  type: string
                  format: date-time
                  example: 2023-01-19:12:00
                updatedAt:
                  type: string
                  format: date-time
                  example: 2023-01-19:12:00
              required:
                - context
                - title
                - userId
                - createdAt
                - updatedAt
       parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the post to update
       responses:
        '200':
          description: Post updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  context:
                    type: string
                    example: Updated the information of context
                  title:
                    type: string
                    example: Updated Title of the context
                  image:
                    type: string
                    format: uri
                    example: https://example.com/updated_image.png
                  userId:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  createdAt:
                    type: string
                    format: date-time
                    example: 2023-01-01T00:12:00
                  updatedAt:
                    type: string
                    format: date-time
                    example: 2023-01-02T00:12:00
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Post not found
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid ID supplied
  /api/v1/activity/{userId}:
     get:
      summary: Get activity log by userId
      description: Endpoint to retrieve the activity log for a user by userId.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the user to get the activity log for
      responses:
        '200':
          description: Activity log retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  activities:
                    type: array
                    items:
                      type: object
                      properties:
                        postId:
                          type: string
                          format: uuid
                          example: 123e4567-e89b-12d3-a456-426614174000
                        action:
                          type: string
                          example: created
                        timestamp:
                          type: string
                          format: date-time
                          example: 2023-01-19:12:00
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid ID supplied
  /api/v1/activity/{activityId}:
    get:
      summary: Get specific activity of the users by activityId
      description: Endpoint to retrieve a specific activity by the user activityId.
      parameters:
        - name: activityId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the activity to get
      responses:
        '200':
          description: Activity retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  activityId:
                    type: string
                    format: uuid
                    example: 789e1234-e56b-78d9-f012-34567890abcd
                  postId:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  action:
                    type: string
                    example: created
                  timestamp:
                    type: string
                    format: date-time
                    example: 2023-01-19:12:00
        '404':
          description: Activity not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: Activity not found
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                   status_code:
                    type: integer
                    example: 400
                   message:
                    type: string
                    example: Invalid request parameter
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/WAHABMUFIDAT1919/hngstage3/1.0.0