openapi: 3.0.0
info:
  title: Notification API
  version: 1.0.0
  description: API for managing user notifications

paths:
  /notifications:
    get:
      summary: Retrieve notifications
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'

    post:
      summary: Create a new notification
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationInput'
      responses:
        '201':
          description: Notification created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'

  /notifications/{id}:
    get:
      summary: Retrieve a specific notification
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'

    put:
      summary: Update a notification's read status
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationUpdate'
      responses:
        '200':
          description: Notification updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'

components:
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        message:
          type: string
        isRead:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        userId:
          type: integer

    NotificationInput:
      type: object
      required:
        - message
        - userId
      properties:
        message:
          type: string
        userId:
          type: integer

    NotificationUpdate:
      type: object
      required:
        - isRead
      properties:
        isRead:
          type: boolean

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

security:
  - BearerAuth: []
